#!/bin/sh

if [ $# -eq 1 ] || [ $# -eq 2 ]
then
	if [ $# -eq 2 ]
	then
		host=$1
		name=$2
	else
		host=$1
		name=$1
	fi

	rm -f certs/$name.*

	tnow=`date +%s`

	days=`expr \( 2147483647 - $tnow \) / 86400`

	sed "s/_SAN_/$host/" csr.conf > $name.conf

	openssl genrsa -out certs/$name.key 4096

	openssl req -new -key certs/$name.key -out $name.csr -config $name.conf -subj "/CN=$host"

	openssl x509 -req -in $name.csr \
		-CA ca/ca.crt -CAkey ca/ca.key -CAcreateserial \
		-days $days -extensions v3_req -extfile $name.conf \
		-out certs/$name.crt

	rm $name.csr

	rm $name.conf
else
	echo 'usage: mkcert <host> [<name>]'
fi
